import { EXTRA_SITUATIONS } from "./extra_situations";
const BASIC_SITUATIONS = [
  {
    contexto: "Social",
    trigger: "Era só uma piada",
    educadora: "Piadas também têm impacto real nas pessoas. O humor pode perpetuar estereótipos prejudiciais.",
    sarcastica: "Sim, hilariante... Já consideraste stand-up comedy? O público adora piadas à custa dos outros.",
    assertiva: "Não achei piada nenhuma. Peço que não repitas.",
    sem_filtro: "Se isso é humor, está fraco. Arranja material novo.",
    seguranca: "Média",
    notas: "Resposta comum para minimizar comentários ofensivos.",
    tags: ["humor", "fronteiras", "respeito"]
  },
  {
    contexto: "Profissional",
    trigger: "Interrupção constante",
    educadora: "Gostava de terminar o meu raciocínio antes de receber contribuições. A comunicação é mais eficaz assim.",
    sarcastica: "Prometo que no fim também aceito comentários. Paciência é uma virtude.",
    assertiva: "Ainda não terminei. Deixa-me concluir, por favor.",
    sem_filtro: "Se me deixares falar talvez consigas acompanhar o raciocínio.",
    seguranca: "Alta",
    notas: "Comum em reuniões quando mulheres são interrompidas.",
    tags: ["reunião", "comunicação", "respeito"]
  },
  {
    contexto: "Profissional",
    trigger: "Mansplaining",
    educadora: "Agradeço a intenção, mas já tenho conhecimento nesta área. Posso contribuir com a minha perspectiva?",
    sarcastica: "Uau, que revelação! Nunca tinha ouvido falar disso nos meus 10 anos de experiência.",
    assertiva: "Sei do que estou a falar. Não preciso de explicação.",
    sem_filtro: "Guarda a aula para quem precisa. Eu não preciso.",
    seguranca: "Alta",
    notas: "Quando um homem explica algo a uma mulher de forma condescendente.",
    tags: ["condenscendência", "carreira", "fronteiras"]
  },
  {
    contexto: "Profissional",
    trigger: "Roubo de ideias",
    educadora: "Fico feliz que a minha sugestão tenha ressonado. Gostava de desenvolver mais essa ideia que apresentei.",
    sarcastica: "Que bom ouvir a minha ideia novamente! Agora com a voz de outra pessoa.",
    assertiva: "Essa foi a minha sugestão. Agradeço o reconhecimento da autoria.",
    sem_filtro: "Essa ideia é minha. Acabaste de a repetir.",
    seguranca: "Alta",
    notas: "Quando alguém se apropria de uma ideia que apresentaste.",
    tags: ["autoria", "reunião", "carreira"]
  },
  {
    contexto: "Profissional",
    trigger: "Tens namorado?",
    educadora: "A minha vida pessoal não é relevante para o contexto profissional em que estamos.",
    sarcastica: "Isso vem no próximo relatório trimestral. Fica atento.",
    assertiva: "Isso não é assunto de trabalho. Voltemos ao tema.",
    sem_filtro: "Isso não te diz respeito. Foco no trabalho.",
    seguranca: "Alta",
    notas: "Pergunta inapropriada em contexto profissional.",
    tags: ["privacidade", "fronteiras", "trabalho"]
  },
  {
    contexto: "Social",
    trigger: "És muito sensível",
    educadora: "Reconhecer problemas não é sensibilidade excessiva. É atenção ao que importa.",
    sarcastica: "Obrigada! A sensibilidade é uma qualidade. Pena nem todos a terem.",
    assertiva: "Não sou sensível. Estou a ser clara sobre o que não aceito.",
    sem_filtro: "Não sou sensível. Tu é que és insensível.",
    seguranca: "Média",
    notas: "Usado para invalidar emoções e preocupações legítimas.",
    tags: ["respeito", "fronteiras", "empatia"]
  },
  {
    contexto: "Social",
    trigger: "Devias sorrir mais",
    educadora: "O meu rosto não está aqui para decoração. Sorrio quando tenho motivo.",
    sarcastica: "Claro! Deixa-me só ativar o modo 'mulher decorativa'. Já está?",
    assertiva: "Sorrio quando quero. Não deves comentar a minha expressão.",
    sem_filtro: "E tu devias falar menos. Mas cá estamos.",
    seguranca: "Média",
    notas: "Expectativa de que mulheres devem parecer sempre agradáveis.",
    tags: ["expressão", "autonomia", "estilo"]
  },
  {
    contexto: "Social",
    trigger: "Não pareces lésbica",
    educadora: "A orientação sexual não tem uma 'aparência'. Os estereótipos limitam a compreensão.",
    sarcastica: "Ah, peço desculpa! Deixei a farda em casa hoje.",
    assertiva: "Não há uma aparência para orientações sexuais. O comentário é inadequado.",
    sem_filtro: "E tu não pareces ignorante, mas olha...",
    seguranca: "Média",
    notas: "Estereótipo sobre aparência e orientação sexual.",
    tags: ["sexualidade", "respeito", "identidade"]
  },
  {
    contexto: "Street",
    trigger: "Catcalling",
    educadora: "Comentários sobre o corpo de estranhas na rua são intimidantes, não elogios.",
    sarcastica: "Impressionante técnica de comunicação. As mulheres devem adorar.",
    assertiva: "Não comentes o meu corpo. Continua o teu caminho.",
    sem_filtro: "Cala-te e segue.",
    seguranca: "Baixa",
    notas: "Assédio verbal em espaços públicos. Prioriza a tua segurança.",
    tags: ["assédio", "rua", "segurança"]
  },
  {
    contexto: "Street",
    trigger: "Dá-me o teu número",
    educadora: "Não dou o meu contacto a desconhecidos. Respeita a minha privacidade.",
    sarcastica: "Claro! É o 0800-NAO-OBRIGADO.",
    assertiva: "Não. E não vou mudar de ideias.",
    sem_filtro: "Não. Afasta-te.",
    seguranca: "Baixa",
    notas: "Pressão para dar informação pessoal a estranhos.",
    tags: ["privacidade", "fronteiras", "rejeição"]
  },
  {
    contexto: "Social",
    trigger: "Para mulher até percebes",
    educadora: "O género não determina capacidade intelectual. Esse tipo de comentário perpetua mitos.",
    sarcastica: "Incrível, não é? É quase como se mulheres também tivessem cérebro!",
    assertiva: "Percebo porque estudei. Não tem nada a ver com género.",
    sem_filtro: "Percebo mais do que tu, claramente.",
    seguranca: "Média",
    notas: "Elogio backhanded que implica que mulheres são menos capazes.",
    tags: ["preconceito", "capacidade", "respeito"]
  },
  {
    contexto: "Profissional",
    trigger: "És agressiva",
    educadora: "Assertividade em mulheres é frequentemente confundida com agressividade. Estou apenas a ser direta.",
    sarcastica: "Engraçado, nos homens chamam a isto 'liderança forte'.",
    assertiva: "Não sou agressiva. Sou assertiva. Há diferença.",
    sem_filtro: "Se achas isto agressivo, não me conheces mesmo.",
    seguranca: "Alta",
    notas: "Duplo padrão: homens são 'assertivos', mulheres são 'agressivas'.",
    tags: ["liderança", "estilo", "carreira"]
  },
  {
    contexto: "Social",
    trigger: "Quando vais ter filhos?",
    educadora: "Decisões sobre maternidade são pessoais e não definem o valor de uma mulher.",
    sarcastica: "Não sei, está no horóscopo de amanhã. Fico atenta.",
    assertiva: "Isso é uma decisão privada minha. Não vou discutir.",
    sem_filtro: "Quando tu deixares de fazer perguntas inconvenientes.",
    seguranca: "Média",
    notas: "Pressão social sobre maternidade.",
    tags: ["maternidade", "família", "privacidade"]
  },
  {
    contexto: "Profissional",
    trigger: "Estás naqueles dias?",
    educadora: "O ciclo menstrual não invalida emoções ou opiniões profissionais. É uma pergunta inapropriada.",
    sarcastica: "Não, estou naquele dia em que não tolero comentários destes.",
    assertiva: "Isso é irrelevante e impróprio. Não repitas.",
    sem_filtro: "Isso não te diz respeito. Nunca.",
    seguranca: "Alta",
    notas: "Usado para desvalorizar opiniões de mulheres no trabalho.",
    tags: ["preconceito", "trabalho", "fronteiras"]
  },
  {
    contexto: "Social",
    trigger: "Vestida assim pedias",
    educadora: "Roupa nunca é consentimento. A responsabilidade de assédio é sempre de quem o comete.",
    sarcastica: "Ah sim, a minha roupa fala! Pediu ela, não eu.",
    assertiva: "Roupa não é convite. O comentário é inaceitável.",
    sem_filtro: "A culpa nunca é da vítima. Revê os teus valores.",
    seguranca: "Média",
    notas: "Culpabilização da vítima pelo vestuário.",
    tags: ["respeito", "consentimento", "roupa"]
  },
  {
    contexto: "Street",
    trigger: "Sorriso, linda",
    educadora: "Pedir que estranhas sorriam na rua é uma forma de controlo social.",
    sarcastica: "O meu rosto, as minhas regras. Próximo!",
    assertiva: "Não me conheces para me dar ordens. Segue em frente.",
    sem_filtro: "Não sou tua amiga. Passa.",
    seguranca: "Baixa",
    notas: "Assédio disfarçado de 'elogio' na rua.",
    tags: ["assédio", "rua", "autonomia"]
  },
  {
    contexto: "Profissional",
    trigger: "Podes tirar as notas?",
    educadora: "Posso, mas gostava de participar activamente na discussão. Podemos rodar essa tarefa?",
    sarcastica: "Claro! E também posso fazer café e sorrir bonito, certo?",
    assertiva: "Prefiro participar na discussão. Alguém pode tirar notas desta vez?",
    sem_filtro: "Não sou secretária. Tira tu as notas.",
    seguranca: "Alta",
    notas: "Atribuição de tarefas administrativas por género.",
    tags: ["trabalho", "reunião", "igualdade"]
  },
  {
    contexto: "Social",
    trigger: "Não sejas mal-educada",
    educadora: "Definir limites não é falta de educação. É autocuidado.",
    sarcastica: "Desculpa, a educação acabou quando o respeito também acabou.",
    assertiva: "Não estou a ser mal-educada. Estou a ser clara.",
    sem_filtro: "Mal-educado é ignorar quando alguém diz não.",
    seguranca: "Média",
    notes: "Usado para manipular mulheres a aceitar comportamentos inadequados.",
    tags: ["fronteiras", "respeito", "manipulação"]
  },
  {
    contexto: "Street",
    trigger: "Andas sozinha?",
    educadora: "Mulheres têm direito a circular livremente. A pergunta é inapropriada.",
    sarcastica: "Não, o meu guarda-costas invisível está aqui.",
    assertiva: "Isso não te diz respeito. Com licença.",
    sem_filtro: "Afasta-te.",
    seguranca: "Baixa",
    notas: "Pode indicar intenções preocupantes. Prioriza a segurança.",
    tags: ["assédio", "segurança", "rua"]
  },
  {
    contexto: "Profissional",
    trigger: "Querida / Fofa",
    educadora: "Prefiro ser tratada pelo meu nome ou título profissional.",
    sarcastica: "É [Nome], na verdade. Está no crachá e no email.",
    assertiva: "O meu nome é [Nome]. Usa-o, por favor.",
    sem_filtro: "Não sou 'querida'. Trata-me pelo nome.",
    seguranca: "Alta",
    notas: "Diminutivos condescendentes em contexto profissional.",
    tags: ["carreira", "respeito", "trabalho"]
  },
  {
    contexto: "Social",
    trigger: "És bonita demais para ser inteligente",
    educadora: "Aparência e inteligência não são mutuamente exclusivas. O comentário é redutor.",
    sarcastica: "Incrível! Consegui ter as duas coisas ao mesmo tempo!",
    assertiva: "Esse comentário é tão errado em tantos níveis.",
    sem_filtro: "E tu és rude demais para eu continuar esta conversa.",
    seguranca: "Média",
    notas: "Estereótipo de que beleza e inteligência não coexistem.",
    tags: ["estereótipo", "capacidade", "respeito"]
  },
  {
    contexto: "Profissional",
    trigger: "Chefe mulher é complicado",
    educadora: "Estudos mostram que equipas diversas são mais bem-sucedidas. O preconceito não tem base.",
    sarcastica: "É, ter competência é mesmo complicado para alguns.",
    assertiva: "Liderança não tem género. O comentário é preconceituoso.",
    sem_filtro: "Complicado é trabalhar com pessoas preconceituosas.",
    seguranca: "Alta",
    notas: "Preconceito contra liderança feminina.",
    tags: ["liderança", "carreira", "preconceito"]
  },
  {
    contexto: "Social",
    trigger: "Isso é coisa de homem",
    educadora: "Interesses e habilidades não têm género. Todos podem gostar do que quiserem.",
    sarcastica: "Deixa ver... não encontro aqui o manual que diz isso.",
    assertiva: "É coisa minha. E gosto muito.",
    sem_filtro: "É coisa de quem quer. E eu quero.",
    seguranca: "Média",
    notas: "Limitação de interesses baseada em género.",
    tags: ["género", "estilo", "igualdade"]
  },
  {
    contexto: "Street",
    trigger: "Posso acompanhar-te?",
    educadora: "Não preciso de companhia. Agradeço mas recuso.",
    sarcastica: "Não, obrigada. Já tenho GPS.",
    assertiva: "Não. Prefiro ir sozinha.",
    sem_filtro: "Não. Afasta-te.",
    seguranca: "Baixa",
    notas: "Insistência de estranhos. Prioriza a sua segurança.",
    tags: ["rua", "fronteiras", "segurança"]
  },
  {
    contexto: "Social",
    trigger: "Relaxa / Acalma-te",
    educadora: "Dizer a alguém para se acalmar geralmente tem o efeito oposto e invalida as suas emoções.",
    sarcastica: "Ah, 'acalma-te', o botão mágico que resolve tudo!",
    assertiva: "Estou calma. E vou expressar o que penso.",
    sem_filtro: "Acalmo-me quando deixares de dizer disparates.",
    seguranca: "Média",
    notas: "Usado para silenciar e invalidar emoções.",
    tags: ["fronteiras", "respeito", "comunicação"]
  },
  {
    contexto: "Profissional",
    trigger: "Pareces cansada",
    educadora: "Comentários sobre aparência física no trabalho são desnecessários. Como posso ajudar-te?",
    sarcastica: "É o look 'trabalhei muito enquanto outros comentavam'.",
    assertiva: "Não precisas de comentar a minha aparência. Estou bem.",
    sem_filtro: "Estou cansada de comentários sobre a minha cara.",
    seguranca: "Alta",
    notas: "Comentário não solicitado sobre aparência física.",
    tags: ["carreira", "trabalho", "fronteiras"]
  },
  {
    contexto: "Social",
    trigger: "Não és como as outras",
    educadora: "Esse 'elogio' na verdade insulta todas as outras mulheres. Não é um cumprimento.",
    sarcastica: "Ah, o famoso 'elogio' que insulta metade da humanidade.",
    assertiva: "Não aceito elogios que rebaixam outras mulheres.",
    sem_filtro: "As 'outras' também não gostam de ti.",
    seguranca: "Média",
    notas: "Falso elogio que divide mulheres.",
    tags: ["sororidade", "respeito", "estereótipo"]
  },
  {
    contexto: "Profissional",
    trigger: "Contrataram-te por quotas",
    educadora: "Fui contratada pelas minhas qualificações. Políticas de diversidade corrigem desigualdades históricas.",
    sarcastica: "Sim, a quota de competência. Muito exclusiva.",
    assertiva: "Fui contratada pelo meu mérito. O comentário é ofensivo.",
    sem_filtro: "E tu foste contratado porquê exatamente?",
    seguranca: "Alta",
    notas: "Minimização de competência de mulheres ou minorias.",
    tags: ["carreira", "mérito", "preconceito"]
  },
  {
    contexto: "Street",
    trigger: "Onde moras?",
    educadora: "Não partilho informação pessoal com desconhecidos.",
    sarcastica: "Na Terra. E tu, de que planeta vieste?",
    assertiva: "Isso não te diz respeito. Com licença.",
    sem_filtro: "Longe de ti. Adeus.",
    seguranca: "Baixa",
    notas: "Nunca partilhes localização com estranhos. Prioriza a segurança-offline.",
    tags: ["privacidade", "segurança", "rua"]
  },
  {
    contexto: "Social",
    trigger: "Gajas são todas iguais",
    educadora: "Generalizações sobre géneros são sempre erradas e prejudiciais.",
    sarcastica: "Claro, somos fabricadas na mesma fábrica. Saímos por encomenda.",
    assertiva: "Generalizações são ignorantes. Não vou aceitar isso.",
    sem_filtro: "E vocês nunca mudam de conversa fiada.",
    seguranca: "Média",
    notas: "Generalização sexista comum.",
    tags: ["sexismo", "respeito", "estereótipo"]
  },
  {
    contexto: "Social",
    trigger: "Estás sempre a reclamar",
    educadora: "Apontar problemas de forma construtiva é necessário para manter relações saudáveis e respeitosas.",
    sarcastica: "Claro, porque engolir sapos em silêncio faz lindamente à pele. Altamente recomendado.",
    assertiva: "Não estou a reclamar. Estou a apontar algo que precisa de ser mudado.",
    sem_filtro: "Se não queres ouvir críticas, faz as coisas bem da primeira vez.",
    seguranca: "Média",
    notas: "Tentativa de invalidar e silenciar opiniões legítimas sobre problemas reais.",
    tags: ["expressão", "comunicação", "respeito"]
  },
  {
    contexto: "Profissional",
    trigger: "Gritas muito / Falas muito alto",
    educadora: "Tenho uma voz projetada e o meu entusiasmo e firmeza técnica não devem ser interpretados como agressividade.",
    sarcastica: "Peço desculpa, vou comprar um regulador de volume sussurrado para as próximas reuniões importantes.",
    assertiva: "A minha entoação é firme porque domino o assunto. Vamos focar-nos no conteúdo técnico.",
    sem_filtro: "Eu falo no tom necessário para que finalmente parem de me ignorar.",
    seguranca: "Alta",
    notas: "Crítica comum ao tom de voz de mulheres em cargos de liderança ou discussão técnica.",
    tags: ["expressão", "presença", "respeito"]
  },
  {
    contexto: "Social",
    trigger: "Mostra o teu telemóvel / Dá o teu Instagram",
    educadora: "As minhas redes e os meus dispositivos são espaços pessoais. Aprecio manter fronteiras claras de privacidade.",
    sarcastica: "Com certeza, queres também o código do meu banco e a cópia da chave de casa?",
    assertiva: "Não dou essa informação a quem não conheço bem. Respeita a minha resposta.",
    sem_filtro: "O telemóvel é meu e a resposta é não. Segue o teu caminho.",
    seguranca: "Média",
    notas: "Pressão invasiva para ceder dados privados ou contas pessoais online.",
    tags: ["privacidade", "fronteiras", "redes"]
  },
  {
    contexto: "Social",
    trigger: "Porque estás tão solteira?",
    educadora: "A realização e felicidade pessoal não dependem de estar numa relação. Estar só é uma escolha consciente.",
    sarcastica: "Estou num namoro sério com a minha liberdade e paz de espírito. Não queremos intermediários.",
    assertiva: "A minha vida pessoal e o meu estado civil não são tópicos que queira discutir aqui.",
    sem_filtro: "Porque prefiro a minha própria excelente companhia e silêncio a curiosidade desnecessária.",
    seguranca: "Média",
    notas: "Invasão de privacidade disfarçada de curiosidade ou simpatia.",
    tags: ["privacidade", "autonomia", "família"]
  },
  {
    contexto: "Social",
    trigger: "As outras mulheres aguentam mais",
    educadora: "Cada pessoa define os seus próprios limites. Comparar tolerâncias anula a empatia necessária para apoiar.",
    sarcastica: "Ótimo para elas! Infelizmente o meu stock de paciência cega esgotou-se esta manhã.",
    assertiva: "Não me guio pelos limites dos outros. Eu decido o que tolero e o que não tolero.",
    sem_filtro: "Elas aguentam porque se calhar não têm alternativa. Eu tenho e escolho não aguentar.",
    seguranca: "Média",
    notas: "Usar comparações para diminuir a queixa ou a legítima reação da mulher.",
    tags: ["empatia", "sororidade", "respeito"]
  },
  {
    contexto: "Social",
    trigger: "Sei exatamente como te sentes",
    educadora: "Cada experiência pessoal tem as suas especificidades. Obrigado, mas preferia partilhar sem que minimizes o que sinto.",
    sarcastica: "Espectacular! Se também souberes os números do Euromilhões, partilha por favor.",
    assertiva: "Agradeço a intenção, mas preferia apenas que me ouvisses sem comparar a tua situação.",
    sem_filtro: "Não sabes nada do que corre na minha pele. Ouve mais e assume menos.",
    seguranca: "Média",
    notas: "Simpatia condescendente que retira o protagonismo da dor ou situação da vítima.",
    tags: ["empatia", "comunicação", "respeito"]
  },
  {
    contexto: "Social",
    trigger: "Falta-te sentido de humor",
    educadora: "O humor que deprecia, diminui ou perpetua humilhações de género deixa de ser uma brincadeira e vira ofensa.",
    sarcastica: "Tenho imenso! Só que o meu humor requer raciocínio e piadas que saíram de 1950 não qualificam.",
    assertiva: "O meu sentido de humor não engloba piadas machistas ou depreciativas. Não acho piada.",
    sem_filtro: "O teu humor parou no jardim de infância. Atualiza o teu repertório de piadas.",
    seguranca: "Média",
    notas: "Acusação clássica que tenta colocar o problema na vítima e não no agressor/piadista.",
    tags: ["humor", "respeito", "fronteiras"]
  },
  {
    contexto: "Profissional",
    trigger: "Estás muito séria, conta uma piada",
    educadora: "A minha postura profissional foca-se na produtividade da equipa e nas tarefas técnicas propostas.",
    sarcastica: "Uma piada? Há uma fantástica sobre pessoas que em vez de trabalharem pedem espetáculos de comédia.",
    assertiva: "Estou concentrada neste assunto profissional. Vamos continuar a reunião.",
    sem_filtro: "Não sou comediante de serviço. Vamos trabalhar que é para isso que estamos aqui.",
    seguranca: "Alta",
    notas: "Expectativa de que mulheres profissionais devem atuar como facilitadoras de boa disposição constante.",
    tags: ["humor", "expressão", "trabalho"]
  }
];

export const SEED_SITUATIONS = [...BASIC_SITUATIONS, ...EXTRA_SITUATIONS];
